version: "3"
services:
  app:
    image: ruby:latest
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/root/wingo
      - bundle:/usr/local/bundle
    working_dir: "/root/wingo"
volumes:
  bundle:
