version: "3"
services:
  app:
    image: ruby:latest
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/root/wingo
      - fly:/root/.fly
      - bundle:/usr/local/bundle
    working_dir: "/root/wingo"
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
volumes:
  bundle:
  fly:
